### ISSUE TITLE
Deploy to Netlify

### ISSUE THREAD

**Issue by tonylomax** [fac-17/UpSkillMe#22]
Guide:
[React week](https://github.com/foundersandcoders/react-week/blob/master/project.md)

- [x] Go to app.netlify.com and login with Github
- [x] Click the "New site from Git" button
- [x] Choose "Github" as your provider (and authorize it)
- [x] Choose the repo you want to deploy
- [x] Choose "Deploy site" (the build settings for CRA should be pre-filled)

**Comment by jackbridger** [comment]
Deployed to Netlify

**Comment by jackbridger** [comment]
upskillme.netlify.com
